### ISSUE TITLE
Lacks og Meta

### ISSUE THREAD

**Issue by HohShenYien** [RileyLeo/rileyleo.github.io#1]
When I was trying to share your site in social media, I noticed that the preview does not have description and image, please add the og meta accordingly:

![image](https://user-images.githubusercontent.com/55322546/209177088-1c949485-1f00-4221-a034-cb76bbc8985b.png)

**Comment by RileyLeo** [comment]
Issue resolved as per  fa957dc53a4bba8f3ef121176a7e950654ed092b

![image](https://user-images.githubusercontent.com/48232039/209204402-2e5b1397-8d7a-4b26-8c07-8a5072c30c64.png)
