### ISSUE TITLE
Lack of logo

### ISSUE THREAD

**Issue by HohShenYien** [RileyLeo/rileyleo.github.io#2]
## Expected Behavior

The website should show a logo for better branding

## Current Behavior

There is no favicon, hence causing the website to display a default logo on the web.

## Possible Solutions

You can get a nice L image, or even a png of your own face and set it as favicon of the website.

**Comment by RileyLeo** [comment]
Issue resolved as per a9d369f9f63cc076b55fa44edf951f2fc099da24
